baseURL: https://dariagneusheva.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
markup:
  goldmark:
    renderer:
params:
  banner: 
    buttonText: Discover 
    subtitle: |-
      Data Science meets R: learn with me step-by-step & enjoy the process
    title: Daria Gneusheva
    blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Mallory St.
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ds.gneusheva@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (07) 501-659-180
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Daria Gneusheva
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/daria_gneusheva/
      - icon: fa-github
        label: GitHub
        url: https://github.com/DariaGneusheva
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/dgneusheva/
  image: ''
  name: Daria
  navigation:
    button1:
      - name: Get Started
        url: blogs
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: About me
        url: post/me
    menu: Menu
    subtitle: ""
    title: Learn R
  tiles:
    enable: yes
    showcase:
      - image: me.jpg
        subtitle: Get to know me
        title: About me
        url: post/me
      - image: data_analysis.jpg
        subtitle: Intermediate Level
        title: Spielberg vs Burton - who is better?
        url: blogs/ipsum
      - image: omega.jpg
        subtitle: Intermediate Level
        title: Gender Pay Gap at Omega - unjustified?
        url: blogs/magna
      - image: climate_change.jpg
        subtitle: Beginner-friendly Level
        title: Believing in Global Warming - does it depend on your political views? 
        url: blogs/tempus
      - image: festival.jpg
        subtitle: Beginner-friendly Level
        title: Where Do People Drink The Most Beer, Wine And Spirits?
        url: blogs/aliquam

  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Learning R doesn't have to be boring and time-consuming. I will walk you step-by-step through diverse real-life and fictional stories, searching for simple answers to complicated problems. Click the button below to explore more content."
    title: Explore more
    url: blogs

markup:
  goldmark:
    renderer:
      unsafe: true
